Resources:
  CreateRichMenuRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: line4tc-${self:custom.groupName}-${self:provider.stage}-CreateRichMenuRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: line4tc-${self:custom.groupName}-${self:provider.stage}-CreateRichMenuPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 
                  - arn:aws:logs:#{AWS::Region}:#{AWS::AccountId}:log-group:/aws/lambda/*:*:*